package couch

import (
	"fmt"
	"strconv"
	"strings"
)

// Rev is a CouchDB revision: "N-hash" where N is the generation number.
// Hashes are generated by NewRevID (revid.go), byte-for-byte CouchDB's
// algorithm, so identical independent writes converge across mixed
// couchgres/CouchDB deployments.
type Rev struct {
	Num  int
	Hash string
}

func (r Rev) String() string {
	return fmt.Sprintf("%d-%s", r.Num, r.Hash)
}

func (r Rev) IsZero() bool {
	return r.Num == 0
}

func ParseRev(s string) (Rev, error) {
	num, hash, ok := strings.Cut(s, "-")
	if ok {
		n, err := strconv.Atoi(num)
		if err == nil && n >= 1 && hash != "" && isAlnum(hash) {
			return Rev{Num: n, Hash: hash}, nil
		}
	}
	return Rev{}, BadRequest("Invalid rev format: " + s)
}

func isAlnum(s string) bool {
	for _, c := range s {
		if (c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < '0' || c > '9') {
			return false
		}
	}
	return true
}
